config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :categories
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/controllers/transactions_controller.rb
class TransactionsController < AuthenticatedController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :set_select, only: [:new, :create, :edit, :update]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = current_user.transactions
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  def set_select
    @categories = current_user.categories.each { |c| c.ancestry = c.ancestry.to_s + (c.ancestry != nil ? "/" : '') + c.id.to_s }
                      .sort {|x,y| x.ancestry <=> y.ancestry }.map{ |c| ["-" * (c.depth - 1) + c.name,c.id] }
                      .unshift(["-- none --", nil])
  end
  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:description, :value, :due_date, :category, :payday,:transaction_type,:user_id,
                                          :category_id,uploads: [])
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="image-preview">
    <% if transaction.uploads.attached? %>
      <%= image_tag transaction.uploads, size: "200x200", class: "image-saved" %>
    <% end %>
    <%= form.file_field :uploads, disable_plugin: true, multiple: true, class: "image-upload" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.select(:transaction_type, options_for_enum(transaction, :transaction_type)) %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_select :due_date %>
  </div>

  <div class="field">
    <%= form.select :category_id, @categories %>
  </div>

  <div class="field">
    <%= form.label :payday %>
    <%= form.date_select :payday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Description</th>
      <th>Value</th>
      <th>Due date</th>
      <th>Category</th>
      <th>Payday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.description %></td>
        <td><%= transaction.value %></td>
        <td><%= transaction.due_date %></td>
        <td><%= transaction.category.name %></td>
        <td><%= transaction.payday %></td>

        <td align="center" style="white-space: nowrap;">
            <%= link_to_show transaction_path(:id => transaction) %>
            <%= link_to_edit edit_transaction_path(:id => transaction) %>
            <%= link_to_delete transaction_path(:id => transaction) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @transaction.value %>
</p>
<p>
  <strong>Tipo:</strong>
  <%= @transaction.transaction_type %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @transaction.due_date %>
</p>

<p>
  <strong>Category:</strong>
  <%= @transaction.category.name %>
</p>

<p>
  <strong>Payday:</strong>
  <%= @transaction.payday %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>