config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :categories
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to edit_user_registration_path do %>
      <i class="fas fa-user-edit"></i><span>Editar usuario</span>
    <% end %>
  </li>
  <li class='nav-item'><%= link_to destroy_user_session_path, :method => 'delete' do %>
      <i class="fas fa-sign-out-alt"></i><span>Logout</span>
    <% end %></li>
<% else %>
  <li class='nav-item'><%= link_to  new_user_session_path do %>
      <i class="fas fa-sign-in-alt"></i></i><span>Login</span>
    <% end %>
  </li>
  <li class='nav-item'><%= link_to  new_user_registration_path do %>
      <i class="fas fa-user-plus"></i></i><span>Registrar</span>
    <% end %>
  </li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li class='nav-item'><%= link_to 'Users', users_path do %>
      <% end %>
    </li>
  <% end %>
<% end %>

app/views/layouts/_navigation_links.html.erb
<li class='nav-item'><%= link_to page_path('about') do %>
    <i class="far fa-question-circle"></i><span></span>
  <% end %>
</li>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <ul>
    <li>
      <%= link_to root_path do %>
        <i class="fas fa-tachometer-alt"></i><span>Dashboard</span>
      <% end %>

    </li>
    <li>
      <%= link_to categories_path do %>
        <i class="fas fa-users"></i><span>Categorias</span>
      <% end %>
    </li>

    <li>
      <%= link_to transactions_path do %>
        <i class="fas fa-money-check-alt"></i><span>Transacoes</span>
      <% end %>
    </li>
    <%= render 'layouts/nav_links_for_auth' %>
    <%= render 'layouts/navigation_links' %>
  </ul>
</div>

app/views/layouts/_topbar.html.erb
<div class="header">
  <a href="#" id="menu-action">
    <i class="fas fa-bars"></i>
    <span>Zamknij</span>
  </a>
  <div class="logo">
    OneAboveAll
  </div>

</div>



<!--<div class="container">-->
<!--  <nav class="navbar navbar-dark bg-inverse">-->
<!--    <ul class="nav navbar-nav clearfix">-->
<!--      <li class="nav-item">-->
<!--        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">-->
<!--          &#9776;-->
<!--        </button>-->
<!--      </li>-->
<!--    </ul>-->
<!--    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">-->
      <%#= link_to "Rails bootstrap", root_path, class: 'navbar-brand' %>
<!--      <ul class="nav navbar-nav">-->
        <%#= render 'layouts/navigation_links' %>
        <%#= render 'layouts/nav_links_for_auth' %>
<!--      </ul>-->
<!--    </div>-->
<!--  </nav>-->
<!--</div>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Oneaboveall" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Oneaboveall" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/topbar' %>
<%= render 'layouts/sidebar' %>
<!-- Content -->
<div class="main">
  <div class="hipsum">
    <div class="jumbotron">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div>
</div>
</div>
</body>
</html>